name: 'Amazon Linux build container'
description: 'Used for building tegola_lambda'
inputs:
  build-cmd:  
    description: 'The build command to execut'
    required: true
    default: 'cd cmd/tegola_lambda && go build -mod vendor -ldflags "-w -X main.Version=${VERSION}"'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build-cmd }}