name: Test tegola_lambda build
on: 
  push:

jobs:

  gen_version:
    name: Generate software version
    runs-on: ubuntu-20.04

    steps:
    # on release we want to use release.tag_name for the version
    - name: Set tegola version (use release.tag_name)
      if: github.event_name == 'release'
      run: echo ${{ github.event.release.tag_name }} > ${{ github.workspace }}/version.txt

    # when it's not a release build use the commit hash for the version tag
    - name: Set tegola version (use commit hash)
      if: github.event_name == 'push'
      run: echo ${{ github.sha }} | cut -c1-7 > ${{ github.workspace }}/version.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: version
        path: ${{ github.workspace }}/version.txt

  build_tegola_lambda:
    name: Build tegola_lambda on Amazon Linux
    needs: gen_version
    runs-on: ubuntu-20.04

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Download version artifact
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Set tegola version
      run: echo "VERSION=$(cat version/version.txt)" >> $GITHUB_ENV

    - name: Build tegola_lambda
      uses: ./.github/actions/amazon-linux-build-action
      with:
        build-cmd: 'ls -la && pwd'
 #       build-cmd: cd /github/workspace/cmd/tegola_lambda && go build -mod vendor -ldflags "-w -X main.Version=${VERSION}"

    # workaround for archives losing permissions 
    # https://github.com/actions/upload-artifact/issues/38
    - name: Zip archive permissions workaround
      run: |
        cd cmd/tegola_lambda
        zip -9 -D tegola.zip tegola_lambda

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: tegola_lambda
        path: cmd/tegola_lambda/tegola.zip

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: cmd/tegola_lambda/tegola.zip
        asset_name: tegola_lambda.zip
        asset_content_type: application/zip
